### ISSUE TITLE
Clarify relationship with other Faker.php

### ISSUE THREAD

**Issue by techdragon** [maetl/faker#1]
What is the relationship between this project and https://github.com/fzaninotto/Faker

To avoid confusion can you include a line saying you are/aren't related to that project. The naming clash makes it hard to tell whats going on.

**Comment by maetl** [comment]
I wasn’t aware of @fzaninotto’s PHP Faker at the time I started this repo (in 2011)—or if I had seen it, it must have been less complete and not so popular than what it is today.

Given that the repository names are capitalized differently, and the respective README files have a completely different prose style and sensibility, I would not have assumed there would be any confusion. There are probably dozens more ports of that same idea into PHP with similar names.

The code in this repo was just a quick extraction from various testing tools and scripts I was using to generate sample data—hence the inclusion of the Color and Product objects, which were _not_ ports of the Perl or Ruby libs.

The best way to tell what’s going on is to look at the number of stars and pull requests. By that metric, there’s no reason to even pay attention to my repo.
